/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DotPattern: typeof import('./../components/dot-pattern/index.vue')['default']
    DotPatternLinearGradient: typeof import('./../components/dot-pattern/dot-pattern-linear-gradient.vue')['default']
    GridPattern: typeof import('./../components/grid-pattern/index.vue')['default']
    GridPatternDashed: typeof import('./../components/grid-pattern/grid-pattern-dashed.vue')['default']
    GridPatternLinearGradient: typeof import('./../components/grid-pattern/grid-pattern-linear-gradient.vue')['default']
    IIcon: typeof import('./../components/i-icon/index.vue')['default']
    NavBar: typeof import('./../components/nav-bar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/svg-icon/index.vue')['default']
    Tabbar: typeof import('./../components/tabbar/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
